name: Build LSPosed Module

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Java Development Kit
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Compile Debug APK
      run: gradle assembleDebug

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: lsposed-module-debug
        path: app/build/outputs/apk/debug/app-debug.apk
